import { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://homeschoolmath.site'
  const lastModified = new Date()

  const routes = [
    '',
    '/about',
    '/addition-practice',
    '/contact',
    '/cookies',
    '/division-practice',
    '/fractions-practice',
    '/how-to-use',
    '/kindergarten-worksheets',
    '/kindergarten-addition-worksheets',
    '/kindergarten-counting-worksheets',
    '/kindergarten-subtraction-worksheets',
    '/grade-1-worksheets',
    '/grade-1-addition-worksheets',
    '/grade-1-subtraction-worksheets',
    '/grade-1-word-problems-worksheets',
    '/grade-2-worksheets',
    '/grade-2-addition-worksheets',
    '/grade-2-subtraction-worksheets',
    '/grade-2-word-problems-worksheets',
    '/grade-3-worksheets',
    '/grade-3-addition-worksheets',
    '/grade-3-subtraction-worksheets',
    '/grade-3-multiplication-worksheets',
    '/grade-3-division-worksheets',
    '/grade-3-word-problems-worksheets',
    '/grade-4-worksheets',
    '/grade-4-multiplication-worksheets',
    '/grade-4-division-worksheets',
    '/grade-4-fractions-worksheets',
    '/grade-4-word-problems-worksheets',
    '/grade-5-worksheets',
    '/grade-5-multiplication-worksheets',
    '/grade-5-division-worksheets',
    '/grade-5-fractions-worksheets',
    '/grade-5-decimals-worksheets',
    '/grade-5-word-problems-worksheets',
    '/grade-6-worksheets',
    '/grade-6-multiplication-worksheets',
    '/grade-6-division-worksheets',
    '/grade-6-percent-worksheets',
    '/grade-6-word-problems-worksheets',
    '/multiplication-practice',
    '/subtraction-practice',
    '/word-problems',
    '/teaching-tips',
    '/resources',
    '/privacy-policy',
    '/terms-of-service',
    '/area-perimeter',
    '/place-value',
  ]

  return routes.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified,
    changeFrequency: route === '' || route.includes('practice') || route.includes('worksheets') ? 'weekly' : 'monthly',
    priority: route === '' ? 1 : route === '/resources' ? 0.9 : route.includes('worksheets') || route.includes('practice') ? 0.8 : 0.7,
  }))
}
